DOC: Fix hyperlink syntax in blog entry
Fix hyperlink syntax in blog entry: add a missing whitespace between the
displayed text and the target URL.

Fixes:
```
/fury/docs/source/posts/2023/2023-01-29-final-report-shivam.rst::
 ERROR: Anonymous hyperlink mismatch: 1 references but 0 targets.
See "backrefs" attribute for IDs.
```

raised for example at:
https://github.com/fury-gl/fury/actions/runs/10530916380/job/29181869908#step:7:551